// $Id$
Drupal.behaviors.listmixer = function() {
  // Read through each preset
  $.each(Drupal.settings.listmixer, function(){
    // If page contains a target block
    if(this.preset_method == 'listmixer_storage_nodes') {
      // Node target finding mechanism #1, The First
      // The view must contain .views-field-nid (generated by adding a field)
      // @TODO add a setting so user can specify the class/field that contains the node data. then they can put it whereever. let it be a full jQuery command.

      // Find the contents of an nid field, store it, and then hide it.
      $('#' + this.interactions.interactions_target_id).find('div.views-field-nid span.field-content').each(function(){
        this.target_nid = $(this).html();
      }).hide();      
      
      
      
      // @TODO: Look up with behaviors to apply to the page
      
      
      // @TODO: Look up which behaviors to load/apply to the target
      
      // @TODO: So the idea will be to build a library of buttons and things, and then load them based on the behavior settings.
      
      this.target_form_class = 'class="listmixer-target-form"';   
      this.target_form_id = 'listmixer-target-'+ this.preset_name;
      this.target_form = '<form id="' + this.target_form_id + '" ' + this.target_form_class + '></form>';
      this.interact = '<input></input>';
      this.submit = '<button>Save</button>';
      
      $('#' + this.interactions.interactions_target_id).append(this.target_form);

      $('#' + this.target_form_id).append(this.interact);
      
      // Add interact button (load js from interact button function)
      $('#' + this.target_form_id).append(this.submit);
      
      // @TODO: connect submit function to push callback and data
      
      // @TODO: add field spec to settings for behaviors
      
      
      
      // options:
      // if view content contains 'nid'...
      // http://11heavens.com/theming-Drupal-6-from-the-module-layer
      
      // semantic view
      // make user add markup with node id -- this ensure they have ultimate control * (definite option)
      // theme preprocess function all nodes add class listmixer-node-#nid
    }
  });
}

Drupal.behaviors.listmixer.push = function() {    
  var callback;
//  callback = Drupal.settings.basePath + 'admin/drag-list/ajax/store/' + Drupal.settings.drag_list.currentList;
  var data;
  
  //$.post(callback, { link_href : $(this).attr('drag_list_value') }, dragListUpdateBlock());

  // preventing entire page from reloading 
  return false;         
}