<?php
// $Id$

/*
 * @file
 */

/**
 * Implementation of hook_listmixer_default_preset().
 * Generate a default listmixer preset setting.
 */
function listmixer_todo_list_add_listmixer_default_preset() {
  $preset = array (
    'preset_name' => 'todo_list_add',
    'preset_description' => 'Add items to a to do list node',
    'preset_method' => 'listmixer_storage_default',
    'preset_enabled' => '1',
    'behaviors' => 
    array (
      'activate' => 
      array (
        'behavior_name' => 'activate_select',
        'behavior_type' => 'activate',
      ),
      'interact' => 
      array (
        'behavior_name' => 'interact_input',
        'behavior_type' => 'interact',
      ),
      'push' => 
      array (
        'behavior_name' => 'push_text',
        'behavior_type' => 'push',
      ),
      'submit' => 
      array (
        'behavior_name' => 'submit_button_refresh',
        'behavior_type' => 'submit',
      ),
    ),
    'interactions' => 
    array (
      'interactions_label' => 'Add a to do list item',
      'interactions_help' => 'Select a to-do list. Then, type your to-do list item. Click \'Save.\'',

      'interactions_container' => 'div#center div.view-to-do-list-current',
/*
      'interactions_inclusions' => 'div.ui-selected',
      'interactions_region' => 'div.views-row',
*/

/*
      'interactions_region' => 'div#selectable-listmixer-main-container-todo_list_add.ui-selectable:has(h2 a.ui-selected)',
      'interactions_inclusions' => '',
*/
      'interactions_region' => 'div#center div.view-to-do-list-current',
      'interactions_inclusions' => 'div.ui-selectable:has(h2 a.ui-selected)',

      'interactions_target_id' => 'div#center div.view-to-do-list-current div.views-row',
      'interactions_target_id_element' => 'h2 a',
      'interactions_target_id_attr' => 'href',
      'interactions_target_field' => 'field_item',

      'interactions_source_id' => '',
      'interactions_source_id_attr' => '',

      'interactions_push_label' => '',
      'interactions_submit_label' => 'Save',
      'interactions_activate_label' => 'Select a to-do list',
      'interactions_interact_label' => '',

      'interactions_source_content_types' => '',
    ),
  );
  return array($preset);
}