<?php
// $Id$

/*
 *******************************************************************************
 * @file listmixer_storage_nodes.module
 * Main module file for List Mixer Node Storage module
 *******************************************************************************
 */
 
include('includes/listmixer_storage_nodes.inc'); 
 
/**
 *  listmixer_storage_register hook implementation
 *  Return this type to the list of storage methods available to the preset selector.
 */
 
function listmixer_storage_nodes_listmixer_storage_register() {
  return array(
    array(
    'name' => 'Nodes', 
    'module' => 'listmixer_storage_nodes',
    'weight' => '-10',
    ),
  );
}

function listmixer_storage_nodes_load_interaction_form($preset) {

  $results = db_query("SELECT * FROM {listmixer_storage_nodes}", array($preset['preset_id']));
  while ($interaction = db_fetch_array($results)) {
    // Only get the first result
    // @TODO: look into what kinds of results might happen.
    break;
  }

  $form = array();
  
  $form['interactionid'] = array(
    '#type' => 'value',
    '#value' => $interaction['interactionid'],
  );
  $form['preset_id'] = array(
    '#type' => 'value',
    '#value' => $interaction['interactionid'],
  );

  $form['interaction_target_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Interaction Target ID'),
    '#default_value' => $interaction['interaction_target_id'],
    '#description' => t('The name of a views block id to be used as a container for storing list data.'),
    '#weight' => 1,
  );
  $all_nodetypes = node_get_types();
  $all_nodetype_options = array();
  foreach ($all_nodetypes as $item) {
    $all_nodetype_options[$item->type] = $item->name;
  }
  $form['interaction_source_content_types'] = array(
      '#type' => 'select',
      '#title' => t('Content types'),
      '#description' => t('Select which content types will be allowed to be added to the list content type.'),
      '#options' => $all_nodetype_options,
      '#default_value' => $interaction['interaction_source_content_types'],
      '#weight' => 2,
  );
  $form['interaction_restrictions'] = array(
      '#type' => 'textarea',
      '#title' => t('Restrict Markup'),
      '#description' => '<p>' .t('Provide a newline separated list of markup targets to exclude. Enter in jQuery compatible format, ex div.view-favorites, form#edit-image.
                         This will restrict interactions on a page to a container or condition.') . '</p>',
      '#default_value' => $interaction['interaction_restrictions'],
      '#weight' => 3,
  );
  $form['interaction_inclusions'] = array(
      '#type' => 'textarea',
      '#title' => t('Include Markup'),
      '#description' => '<p>' .t('Provide a newline separated list of markup targets to exclude. Enter in jQuery compatible format, ex div.view-favorites, form#edit-image.
                        This will make interaction available to containers and conditions, especially if they were partly overridden by the restrictions.') . '</p>',
      '#default_value' => $interaction['interaction_inclusions'],
      '#weight' => 4,
  );
  return $form;
}