<?php
// $Id$

/*
 * @file
 */

/**
 * Implementation of hook_listmixer_default_preset().
 * Generate a default listmixer preset setting.
 */
function listmixer_photoset_sortable_sort_listmixer_default_preset() {
  $preset = array(
    'preset_name' => 'photoset_sortable_sort',
    'preset_description' => 'Sort photos in a photo set.',
    'preset_method' => 'listmixer_storage_default',
    'preset_enabled' => '1',
    'behaviors' =>
    array(
      'activate' => 'activate_button',
      'interact' => 'interact_sort',
      'push' => 'push_nodereference',
      'submit' => 'submit_button',
    ),
    'interactions' =>
    array(
        'interactions_label' => 'Sort photoset',
        'interactions_help' => 'You are sorting your photoset. Then click save.',

        'interactions_container' => 'div#center div.view-photo-gallery-sortable div.attachment div.view-photo-gallery-sortable',
        'interactions_region' => 'div.field-field-reference-photo div.field-items',
        'interactions_inclusions' => 'div.field-item',

        'interactions_source_id' => 'a',
        'interactions_source_id_attr' => 'href',

        'interactions_target_id' => 'div.view-photo-gallery-sortable div.attachment div.view-content h2 a',
        'interactions_target_id_element' => '',
        'interactions_target_id_attr' => 'href',
        'interactions_target_field' => 'field_reference_photo',


        'interactions_source_content_types' => '',

        'interactions_interact_label' => '',
        'interactions_push_label' => '',
        'interactions_submit_label' => '',
        'interactions_activate_label' => '',

    ),
  );
  return array($preset);
}