<?php
// $Id$

/*
 * @file
 */

/**
 * Implementation of hook_listmixer_default_preset().
 * Generate a default listmixer preset setting.
 */
function listmixer_demo_favorite_links_listmixer_default_preset() {
  $preset = array(
    'preset_name' => 'favorite_links',
    'preset_description' => 'Save links from any Drupal page into a link node.',
    'preset_method' => 'listmixer_storage_default',
    'preset_enabled' => '1',
    'behaviors' =>
    array(
      'activate' => 'activate_button',
      'interact' => 'interact_checkbox',
      'push' => 'push_link',
      'submit' => 'submit_button',
    ),
    'interactions' =>
    array(

        'interactions_target_id' => 'div#block-views-favorite_links-block_1 div.views-field-nid span.field-content',
        'interactions_region' => 'body:has(div#block-views-favorite_links-block_1)',
        'interactions_inclusions' => 'div#center div.node div.field-item:has(a.imagecache)',
        'interactions_container' => 'body:has(div#block-views-favorite_links-block_1)',
        'interactions_source_id' => 'a.imagecache',
        'interactions_target_field' => 'field_link',
        'interactions_help' => 'Click \'Activate.\' Then check the checkboxes to save links to your list.',
        'interactions_source_content_types' => '',
        'interactions_label' => 'Save links on this page to your favorites list.',
        'interactions_interact_label' => '',
        'interactions_push_label' => '',
        'interactions_submit_label' => '',
        'interactions_activate_label' => '',
        'interactions_source_id_attr' => 'href',
        'interactions_target_id_attr' => '',
        'interactions_target_id_element' => '',

    ),
  );
  return array($preset);
}