<?php
// $Id$

/*
 * @file 
 */

/**
 * Implementation of hook_listmixer_default_preset
 * Generate a default listmixer preset setting.
 */
function listmixer_demo_photoset_sortable_add_listmixer_default_preset() {
  $preset = array (
    'preset_name' => 'photoset_sortable_add',
    'preset_description' => 'This connects the node ids from a gallery view to a view attachment.',
    'preset_method' => 'listmixer_storage_default',
    'preset_enabled' => '0',
    'behaviors' => 
    array (
      'activate' => 'activate_load',
      'interact' => 'interact_checkbox',
      'push' => 'push_nodereference',
      'submit' => 'submit_button',
    ),
    'interactions' => 
    array (
      0 => 
      array (
        'interactions_target_id' => 'div.view-display-id-page_1 div.attachment div.view-content h2 a',
        'interactions_region' => 'div.view-display-id-page_1',
        'interactions_inclusions' => 'table.views-view-grid td',
        'interactions_container' => 'div.view-display-id-page_1',
        'interactions_source_id' => 'div.views-field-nid span.field-content',
        'interactions_target_field' => 'field_reference_photo',
        'interactions_help' => 'You are making a photoset. Click the checkboxes to select images to save into your photo set. Then click save.',
        'interactions_source_content_types' => '',
        'interactions_label' => 'Make a photoset',
        'interactions_interact_label' => 'Add Label',
        'interactions_push_label' => 'Push Label',
        'interactions_submit_label' => 'Save Label',
        'interactions_activate_label' => 'Activate Label',
        'interactions_source_id_attr' => '',
        'interactions_target_id_attr' => 'href',
        'interactions_target_id_element' => '',
      ),
    ),
  );
  return array($preset);
}