<?php
// $Id$

/*
 *******************************************************************************
 * @file listmixer_storage_taxonomy.module
 * Main module file for List Mixer Taxonomy Storage module
 *******************************************************************************
 */
/**
 *  listmixer_storage_register hook implementation
 *  Return this type to the list of storage methods available to the preset selector.
 */
 
function listmixer_storage_taxonomy_listmixer_storage_register() {
  return array(
    t('Taxonomy'), 
    'listmixer_storage_taxonomy',
  );
}


/* This is just a placeholder until the rest of the module is worked out.

Basically, there will be a table that stores terms for lists.

When an ajax function is submitted, instead of saving data to a node, the node
itself will be updated with a term.

This could be extended to assign terms to fields in Drupal 7, allowing any field
to be added to a list.

This storage method is mainly here to demonstrate that there are different ways
to store the data, and that information about them, and functions would need
to be different.

*/